---
title: "Codebook - Deliberation Across The World"
author: "Fabio Votta"
date: "11 November 2017"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r chunks, include=FALSE}
#Default Options - kann bei Gebrauch ge?ndert werden
knitr::opts_chunk$set(echo = T # Whether to display code along with its results
                      , eval = T # Whether to evaluate the code and include its results
                      , results = "asis" # this at deafult is in end much more efficient
                      , cache = F # Whether to cache results for future renders (efficient!)
                      , warning = F # Whether to display errors
                      , message = F # Whether to display messages
                      , error = F # maybe turn on
                      , tidy = F # Whether to reformat code in a tidy way when displaying it
                      , fig.width = 6 #plot width at 6
                      , fig.height = 4 #plot height at 4
                      , fig.align = "center" #plot alignment center
                      )

options(xtable.comment = FALSE)
```

```{r setup}
pacman::p_load(tidyverse, haven, sjPlot, sjmisc,
                     forcats, weights, car,
                     survey, reshape2, favstats,
                     magrittr, knitr)

```

```{r, echo = F}
# Loading the URLs

singles <- dir("singles")

for (jj in singles) {
  load(paste0("singles/", jj))
}

```


# Codebook


```{r}
view_df(afro_5, hide.progress = T) # aus dem sjPlot package
view_df(afro_6, hide.progress = T) # aus dem sjPlot package

view_df(latino_2013, hide.progress = T) # aus dem sjPlot package
view_df(latino_2015, hide.progress = T) # aus dem sjPlot package

view_df(wvs, hide.progress = T) # aus dem sjPlot package

view_df(americas_, hide.progress = T) # aus dem sjPlot package
view_df(canada_, hide.progress = T) # aus dem sjPlot package

view_df(asian_3, hide.progress = T)

view_df(myanmar, hide.progress = T)
view_df(philip   , hide.progress = T)
view_df(taiwan   , hide.progress = T)
view_df(thai     , hide.progress = T)
view_df(malay    , hide.progress = T)
view_df(singapore, hide.progress = T)
view_df(sk       , hide.progress = T)
view_df(cambodia , hide.progress = T)


view_df(ESS, hide.progress = T)
```

