---
title: "summaries"
author: "Fabio Votta"
date: "12 November 2017"
output: html_document
---

```{r chunks, include=FALSE}
#Default Options - kann bei Gebrauch ge?ndert werden
knitr::opts_chunk$set(echo = T # Whether to display code along with its results
                      , eval = T # Whether to evaluate the code and include its results
                      , results = "asis" # this at deafult is in end much more efficient
                      , cache = F # Whether to cache results for future renders (efficient!)
                      , warning = F # Whether to display errors
                      , message = F # Whether to display messages
                      , error = F # maybe turn on
                      , tidy = F # Whether to reformat code in a tidy way when displaying it
                      , fig.width = 6 #plot width at 6
                      , fig.height = 4 #plot height at 4
                      , fig.align = "center" #plot alignment center
                      )

options(xtable.comment = FALSE)
```

```{r setup}
pacman::p_load(tidyverse, haven, sjPlot, sjmisc,
                     forcats, weights, car,
                     survey, reshape2, favstats,
                     magrittr, knitr)

```

```{r, echo = F}
# Loading the URLs


afro5_url <- url("https://github.com/favstats/database_delib/raw//master/afro5.RData")
afro6_url <- url("https://github.com/favstats/database_delib/raw//master/afro6.RData")

latino2013_url <- url("https://github.com/favstats/database_delib/raw//master/latino2013.RData")
latino2015_url <- url("https://github.com/favstats/database_delib/raw//master/latino2015.RData")

wvs_raw_url <- url("https://github.com/favstats/database_delib/raw//master/wvs_raw.RData")

americas_url <- url("https://github.com/favstats/database_delib/raw//master/americas.RData")
bolivia_url <- url("https://github.com/favstats/database_delib/raw//master/bolivia.RData")
canada_url <- url("https://github.com/favstats/database_delib/raw//master/canada.RData")

asian_raw_url <- url("https://github.com/favstats/database_delib/raw//master/asian_raw.RData")
myanmar_raw_url <- url("https://github.com/favstats/database_delib/raw//master/myanmar_raw.RData")
mongolia_raw_url <- url("https://github.com/favstats/database_delib/raw//master/mongolia_raw.RData")
philip_raw_url <- url("https://github.com/favstats/database_delib/raw//master/philip_raw.RData")
taiwan_raw_url <- url("https://github.com/favstats/database_delib/raw//master/taiwan_raw.RData")
thai_raw_url <- url("https://github.com/favstats/database_delib/raw//master/thai_raw.RData")
malay_raw_url <- url("https://github.com/favstats/database_delib/raw//master/malay_raw.RData")
singapore_raw_url <- url("https://github.com/favstats/database_delib/raw//master/singapore_raw.RData")
sk_raw_url <- url("https://github.com/favstats/database_delib/raw//master/sk_raw.RData")
cambodia_raw_url <- url("https://github.com/favstats/database_delib/raw//master/cambodia_raw.RData")

ESS_raw_url <- url("https://github.com/favstats/database_delib/blob/master/ESS_raw.Rdata?raw=true")

vdems_start_url <- url("https://github.com/favstats/database_delib/raw//master/vdems_start.Rdata")

qog_url <- url("https://github.com/favstats/database_delib/raw//master/qog.Rdata")

```


# Datencoding

```{r, echo = F}
load(afro5_url)

delete_na_afro <- function(x) {
  x <- Recode(x, "9 = NA;
            98 = NA;
            99 = NA;
            -1 = NA")
  return(x)
} # Funktion um die NAs im Afro Datensatz zu bestimmen

# alle Variablen
afro_5 <- afro5 %>%
  rename(
    educ = Q97, # Variablen umbenennen
    income = Q3B,
    sex = Q101,
    work = Q96,
    trust_gov = Q59A,
    trust_parliament = Q59B,
    trust_police = Q59H,
    trust_courts = Q59J,
    demtoday = Q46A
  ) %>%
  mutate_at(
    vars(
      income, trust_gov, trust_parliament,
      trust_police, trust_courts, work
    ),
    delete_na_afro
  ) %>% # NAs deleten
  mutate(
    sex = sex - 1, # sex (0/1) codieren
    work = Recode(
      work, # work (0/1) codieren
      "1 = 0;
       2 = 1;
       3 = 1"
    ),
    age = Recode(
      Q1, # missing values l?schen
      "-1 = NA;
      998 = NA;
      999 = NA"
    ),
    demtoday = Recode(
      demtoday,
      "-1 = NA;
       98 = NA;
       99 = NA"
    ),
    educ = Recode(
      educ,
      "-1 = NA;
       98 = NA;
       99 = NA;
      999 = NA"
    ),
    cntry = to_label(COUNTRY_ALPHA),
    year = as.numeric(format(DATEINTR, "%Y"))
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )


load(afro6_url)

afro_6 <- afro6 %>%
  rename(
    educ = Q97,
    income = Q4B,
    sex = Q101,
    work = Q95,
    trust_gov = Q52A,
    trust_parliament = Q52B,
    trust_police = Q52H,
    trust_courts = Q52J,
    demtoday = Q40
  ) %>%
  mutate_at(
    vars(
      income, demtoday, trust_gov,
      trust_parliament, trust_police,
      trust_courts, work
    ),
    delete_na_afro
  ) %>% # NAs deleten
  mutate(
    sex = sex - 1, # sex (0/1) codieren
    work = Recode(
      work, # work (0/1) codieren
      "1 = 0;
       2 = 1;
       3 = 1"
    ),
    age = Recode(
      Q1, # missing values l?schen
      "-1 = NA;
      998 = NA;
      999 = NA"
    ),
    educ = Recode(
      educ,
      "-1 = NA;
       98 = NA;
       99 = NA;
      999 = NA"
    ),
    demtoday = Recode(
      demtoday,
      "8 = NA"
    ),
    cntry = to_label(COUNTRY_R5List),
    year = as.numeric(format(DATEINTR, "%Y"))
  ) %>%
  #  mutate_at(vars(income, demtoday, educ, age,
  #                 trust_gov, trust_parliament,
  #                 trust_police, trust_courts),
  #            as.character) %>%
  #  mutate_at(vars(income, demtoday, educ, age,
  #                 trust_gov, trust_parliament,
  #                 trust_police, trust_courts),
  #            as.numeric) %>%
  select(
    cntry, year, age, sex, income,
    educ, work, demtoday,
    trust_gov, trust_parliament,
    trust_police, trust_courts
  ) 




load(latino2013_url)

latino_2013 <- latino2013 %>%
  rename(
    educ = REEDUC_1,
    income = S6,
    demtoday = P50TGB.A,
    age = S11
  ) %>%
  mutate(
    sex = S10 - 1, # sex variable erstellen
    cntry = to_label(IDENPA), # cntry variable erstellen
    trust_gov = 5 - P26TGB.B,
    trust_parliament = 5 - P26TGB.C,
    trust_police = 5 - P28TGB.B,
    trust_courts = 5 - P26TGB.E,
    year = 2013,
    income = 5 - income,
    work = Recode(
      S19.A,
      "2 = 1;
       3 = 1;
       4 = 0;
       5 = 0;
       6 = 0;
       7 = 0"
    )
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )


load(latino2015_url)

latino_2015 <- latino2015 %>%
  mutate(sex = S12 - 1) %>% # sex variable erstellen
  rename(
    educ = REEDUC_1,
    income = S4,
    demtoday = P17STGBS,
    age = S13
  ) %>%
  mutate(
    trust_gov = 5 - P16ST.G,
    trust_parliament = 5 - P16ST.F,
    trust_police = 5 - P16TGB.B,
    trust_courts = 5 - P16ST.H,
    work = Recode(
      S21.A,
      "2 = 1;
       3 = 1;
       4 = 0;
       5 = 0;
       6 = 0;
       7 = 0"
    ),
    cntry = to_label(IDENPA),
    income = 5 - income,
    year = 2015
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )


load(wvs_raw_url)

wvs <- wvs_raw %>%
  rename(
    educ = V248,
    income = V239,
    demtoday = V141,
    age = V242,
    year = V262
  ) %>%
  mutate(
    sex = V240 - 1, # sex variable erstellen
    trust_gov = 5 - V115,
    trust_parliament = 5 - V117,
    trust_police = 5 - V113,
    trust_courts = 5 - V114,
    work = Recode(
      V229,
      "2 = 1;
       3 = 1;
       4 = 0;
       5 = 0;
       6 = 0;
       7 = 0;
       8 = 0"
    ),
    cntry = to_label(V2)
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday,
    trust_gov, trust_parliament,
    trust_police, trust_courts
  )




load(americas_url)

americas_ <- americas %>%
  mutate(cntry = to_label(pais)) %>%
  select(
    cntry, ocup4a, ed, q10new, q1, q2,
    b10a, b13, b18, b21a, n3, year
  ) %>%
  rename(
    work = ocup4a,
    educ = ed,
    income = q10new,
    sex = q1,
    age = q2,
    trust_courts = b10a,
    trust_parliament = b13,
    trust_police = b18,
    trust_gov = b21a,
    demtoday = n3
  ) %>%
  mutate(
    sex = sex - 1, # sex variable erstellen
    work = Recode(
      work,
      "2 = 1;
       3 = 1;
       4 = 0;
       5 = 0;
       6 = 0;
       7 = 0"
    )
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )


load(bolivia_url)

bolivia_ <- bolivia %>%
  mutate(cntry = to_label(pais)) %>%
  select(
    cntry, ocup4a, ed, q10new, q1, q2,
    b10a, b13, b18, b21a, n3, year
  ) %>%
  rename(
    work = ocup4a,
    educ = ed,
    income = q10new,
    sex = q1,
    age = q2,
    trust_courts = b10a,
    trust_parliament = b13,
    trust_police = b18,
    trust_gov = b21a, # viele missing values
    demtoday = n3
  ) %>%
  mutate(
    sex = sex - 1, # sex variable erstellen
    work = Recode(
      work,
      "2 = 1;
       3 = 1;
       4 = 0;
       5 = 0;
       6 = 0;
       7 = 0"
    )
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )


load(canada_url)

canada_ <- canada %>%
  mutate(cntry = to_label(pais)) %>%
  select(
    cntry, exc13, education, q10, q1, q2,
    b10a, b13, b18, b21a, n3, year
  ) %>%
  rename(
    work = exc13,
    educ = education,
    income = q10,
    sex = q1,
    age = q2,
    trust_courts = b10a,
    trust_parliament = b13,
    trust_police = b18,
    trust_gov = b21a,
    demtoday = n3
  ) %>%
  mutate(
    sex = sex - 1, # sex variable erstellen
    work = work - 1,
    income = ifelse(income == 88, NA, income)
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  )




load(asian_raw_url)

delete_na_asian <- function(x) {
  x <- Recode(
    x,
    "-2 = NA;
      7 = NA;
      8 = NA;
      9 = NA;
     97 = NA;
     98 = NA;
     99 = NA;
     -1 = NA"
  )

  return(x)
} # Funktion um die NAs im asian Datensatz zu bestimmen

asian_3 <- asian_raw %>%
  rename(
    educ = se5,
    trust_gov = q9,
    trust_parliament = q11,
    trust_police = q14,
    trust_courts = q8,
    sex = se2,
    income = se13a,
    work = se9
  ) %>%
  mutate_at(
    vars(
      income, trust_gov, trust_parliament,
      trust_police, trust_courts, work, sex
    ),
    delete_na_asian
  ) %>% # NAs deleten
  mutate(
    trust_gov = 5 - trust_gov,
    trust_parliament = 5 - trust_parliament,
    trust_police = 5 - trust_police,
    trust_courts = 5 - trust_courts,
    sex = sex - 1, # sex (0/1) codieren
    income = Recode(
      income,
      "0 = NA"
    ),
    income = 5 - income,
    work = Recode(
      work, # work (0/1) codieren
      "2 = 0"
    ),
    age = Recode(
      se3a, # missing values l?schen
      "-1 = NA"
    ),
    demtoday = Recode(
      q91,
      "-1 = NA;
       97 = NA;
       98 = NA;
       99 = NA"
    ),
    educ = Recode(
      educ,
      "-1 = NA;
       98 = NA;
       99 = NA"
    ),
    cntry = to_label(country),
    year = as.numeric(format(ir9, "%Y"))
  ) %>%
  select(
    cntry, year, age, sex, income, educ, work, demtoday, 
    trust_gov, trust_parliament, trust_police, trust_courts
  ) 


load(myanmar_raw_url)

needed <- function(data) {
  ss <- data %>%
    rename(
      educ = se5,
      trust_gov = q9,
      trust_parliament = q11,
      trust_police = q14,
      trust_courts = q8,
      sex = se2,
      income = se13a,
      work = se9
    ) %>%
    mutate_at(
      vars(
        trust_gov, trust_parliament,
        trust_police, trust_courts, work, sex
      ),
      delete_na_asian
    ) %>% # NAs deleten
    mutate(
      trust_gov = 5 - trust_gov,
      trust_parliament = 5 - trust_parliament,
      trust_police = 5 - trust_police,
      trust_courts = 5 - trust_courts,
      sex = sex - 1, # sex (0/1) codieren
      income = Recode(
        income,
        "0 = NA;
        97 = NA;
        98 = NA;
        99 = NA;
        -1 = NA"
      ),
      work = Recode(
        work, # work (0/1) codieren
        "2 = 0"
      ),
      age = Recode(
        se3_2, # missing values l?schen
        "-1 = NA"
      ),
      demtoday = Recode(
        q94,
        "-1 = NA;
         97 = NA;
         98 = NA;
         99 = NA"
      ),
      educ = Recode(
        educ,
        "-1 = NA;
         98 = NA;
         99 = NA"
      ),
      cntry = to_label(country),
      year = year
    ) %>%
    select(
      cntry, year, age, sex, income, educ, work, demtoday, 
      trust_gov, trust_parliament, trust_police, trust_courts
    )
  
  return(ss)
}

myanmar <- needed(myanmar_raw)

load(mongolia_raw_url)
load(philip_raw_url)
load(taiwan_raw_url)
load(thai_raw_url)
load(malay_raw_url)
load(singapore_raw_url)
load(sk_raw_url)
load(cambodia_raw_url)

mongolia  <- needed(mongolia_raw)
philip    <- needed(philip_raw)

thai      <- needed(thai_raw)
malay     <- needed(malay_raw)
singapore <- needed(singapore_raw) # Singapore hat extrem viele Missing values
sk        <- needed(sk_raw)
cambodia  <- needed(cambodia_raw)


taiwan <- taiwan_raw %>%
    rename(
      educ = se5,
      trust_gov = q9,
      trust_parliament = q11,
      trust_police = q14,
      trust_courts = q8,
      sex = se2,
      income = se14a,
      work = se9
    ) %>%
    mutate_at(
      vars(
        income, trust_gov, trust_parliament,
        trust_police, trust_courts, work, sex
      ),
      delete_na_asian
    ) %>% # NAs deleten
    mutate(
      trust_gov = 5 - trust_gov,
      trust_parliament = 5 - trust_parliament,
      trust_police = 5 - trust_police,
      trust_courts = 5 - trust_courts,
      sex = sex - 1, # sex (0/1) codieren
      income = Recode(
        4 - income,
        "8 = NA;
         9 = NA"
      ),
      work = Recode(
        work, # work (0/1) codieren
        "2 = 0"
      ),
      age = Recode(
        se3_2, # missing values l?schen
        "-1 = NA"
      ),
      demtoday = Recode(
        q94,
        "-1 = NA;
         97 = NA;
         98 = NA;
         99 = NA"
      ),
      educ = Recode(
        educ,
        "-1 = NA;
         98 = NA;
         99 = NA"
      ),
      cntry = to_label(country),
      year = year
    ) %>%
    select(
      cntry, year, age, sex, income, educ, work, demtoday, 
      trust_gov, trust_parliament, trust_police, trust_courts
    )

load(ESS_raw_url)

ESS <- ESS_raw %>%
  rename(
    demtoday = dmcntov,
    age = agea,
    year = inwyys,
    trust_gov = trstplt,
    trust_parliament = trstprl,
    trust_police = trstplc,
    trust_courts = trstlgl
  ) %>%
  mutate(
    income = 5 - hincfel,
    educ = Recode(
      eisced,
      "55 = NA"
    ),
    work = ifelse(mnactic == 1, 1, 0),
    sex = gndr - 1, # sex variable erstellen
    cntry = to_label(cntry)
  )  %>% 
  select(
    cntry, year, age, sex, income, educ, work, demtoday, trust_gov, trust_parliament,
    trust_police, trust_courts
  )


```



# Description

```{r pressure, results="markup"}


afro_5 %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
afro_6 %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
latino_2013 %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
latino_2015 %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
wvs %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
americas_ %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
bolivia_ %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
canada_ %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
asian_3 %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
myanmar %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
mongolia %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
philip %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
taiwan %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
thai %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
malay %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
singapore %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
sk %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
cambodia %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()
ESS %>%
  descr() %>%
  remove_var(type, se, md, trimmed, skew, kurtosis) %>%
  kable()


```


