---
title: "regressions"
output: html_notebook
---
# Loading in Functions

```{r}
vif.mer <- function (fit) {
  ## adapted from rms::vif
  
  v <- vcov(fit)
  nam <- names(fixef(fit))
  
  ## exclude intercepts
  ns <- sum(1 * (nam == "Intercept" | nam == "(Intercept)"))
  if (ns > 0) {
    v <- v[-(1:ns), -(1:ns), drop = FALSE]
    nam <- nam[-(1:ns)]
  }
  
  d <- diag(v)^0.5
  v <- diag(solve(v/(d %o% d)))
  names(v) <- nam
  v
}
```


# Loading the Packages

```{r}

#pacman::p_install_gh("favstats/favstats")
pacman::p_load(tidyverse, haven, sjPlot, sjmisc, sjstats,
                     forcats, weights, car, lme4,
                     countrycode, ggthemes,
                     survey, reshape2, favstats,
                     magrittr, rlist)
```

# Loading in Data

```{r}
load("data/combined.Rdata")

combined_dem <- combined %>% 
  filter(regime == "demo")

combined_aut <- combined %>% 
  filter(regime != "demo")

combined
```

# plot_models2

```{r}
plot_models2 <- function(..., exponentiate, std.est = NULL, rm.terms = NULL, 
          title = NULL, m.labels = NULL, legend.title = "Dependent Variables", 
          legend.pval.title = "p-level", axis.labels = NULL, axis.title = NULL, 
          axis.lim = NULL, wrap.title = 50, wrap.labels = 25, wrap.legend.title = 20, 
          grid.breaks = NULL, geom.size = 3, geom.spacing = 0.4, geom.colors = "Set1", 
          show.values = FALSE, show.legend = TRUE, show.intercept = FALSE, 
          show.p = TRUE, p.shape = FALSE, vline.type = 2, vline.color = "grey70", 
          digits = 2, facet.grid = FALSE, thatorder = NULL, plot_colors = c("green","green","green","green","green","green",
 "blue","blue","blue","blue","blue","blue",
 "red","red","red","red","red","red"), col_mods = NULL, labelv = -0.5, labelh = -1.1, labelsize = 2) 
{
  
  is_merMod <- function(fit) {
    inherits(fit, c("lmerMod", "glmerMod", "nlmerMod", "merModLmerTest"))
  }
  
  #' @importFrom sjmisc str_contains
  get_glm_family <- function(fit) {
    c.f <- class(fit)
    
    # do we have glm? if so, get link family. make exceptions
    # for specific models that don't have family function
    if (any(c.f %in% c("lme", "plm"))) {
      fitfam <- ""
      logit_link <- FALSE
    } else {
      fitfam <- stats::family(fit)$family
      logit_link <- stats::family(fit)$link == "logit"
    }
    
    # create logical for family
    binom_fam <- fitfam %in% c("binomial", "quasibinomial")
    poisson_fam <- fitfam %in% c("poisson", "quasipoisson") ||
      sjmisc::str_contains(fitfam, "negative binomial", ignore.case = T)
    
    list(is_bin = binom_fam, is_pois = poisson_fam, is_logit = logit_link)
  }
  
  # return names of objects passed as ellipses argument
  dot_names <- function(dots) unname(unlist(lapply(dots, as.character)))
  
  
  #' @importFrom tidyr nest
  #' @importFrom dplyr select filter
  #' @importFrom stats complete.cases
  #' @importFrom rlang .data
  get_grouped_data <- function(x) {
    # nest data frame
    grps <- tidyr::nest(x)
    
    # remove NA category
    cc <- grps %>%
      dplyr::select(-.data$data) %>%
      stats::complete.cases()
    
    # select only complete cases
    grps <- grps %>% dplyr::filter(!! cc)
    
    # arrange data
    if (length(attr(x, "vars", exact = T)) == 1)
      reihe <- order(grps[[1]])
    else
      reihe <- order(grps[[1]], grps[[2]])
    grps <- grps[reihe, ]
    
    grps
  }
  
  
  str_ends_with <- function(x, .match) {
    l <- nchar(x)
    n <- nchar(.match)
    m <- substr(x, pmax(1, l - n + 1), l)
    which(m == .match)
  }
  
  input_list <- tibble::lst(...)
  if (length(input_list) == 1 && class(input_list[[1]]) == 
      "list") 
    input_list <- purrr::map(input_list[[1]], ~.x)
  if (missing(exponentiate)) 
    exponentiate <- inherits(input_list[[1]], c("glm", "glmerMod", 
                                                "glmmTMB"))
  if (!any(inherits(input_list[[1]], c("lm", "lmerMod", "lme", "merModLmerTest"), 
                    which = TRUE) == 1)) 
    std.est <- NULL

#purrr::map(input_list, ~summary(.x))
#summary(input_list)
#s$coefficients[,5]
#if (!show.intercept) 
#  fl <- purrr::map(fl, ~dplyr::slice(.x, -1))
#if (!is.null(std.est)) {
#  
  get_p_stars <- function(pval) {
    dplyr::case_when(
      is.na(pval) ~ "",
      pval < 0.001 ~ "***",
      pval < 0.01 ~ "**",
      pval < 0.05 ~ "*",
      pval < 0.10 ~ "^",
      TRUE ~ ""
    )
  }
  
#    fl <- fl %>% purrr::map(~sjstats::std_beta(.x, 
#                                 type = std.est)) %>% 
#                    purrr::map(~sjmisc::var_rename(.x, 
#                   std.estimate = "estimate")) %>% 
#      purrr::map2(input_list,  ~tieele::add_column(.x, 
#                    p.value = sjstats::get_model_pval(.y)[["p.value"]][-1]))
#  }
input_list2 <- input_list %>% 
  purrr::map(~sjstats::std_beta(.x, type = std.est)) %>% 
  purrr::map(~sjmisc::var_rename(.x,  std.estimate = "estimate")) 

input_list2  <- purrr::map(input_list2 , ~dplyr::slice(.x, -1))

nineties <- function(x) {
  x$conf.high2 <- x$estimate + 1.645 * x$std.error
  x$conf.low2 <- x$estimate - 1.645 * x$std.error
  s <- tibble(x$conf.high2,x$conf.low2)
  names(s) <- c("conf.high2","conf.low2")
  s
}

input_list2 <- purrr::map(input_list2 , ~nineties(.x)) %>%  purrr::map2(input_list2, cbind) 


fl <- input_list2 %>% 
  purrr::map2(input_list, ~tibble::add_column(.x, p.value = sjstats::p_value(.y)[["p.value"]][-1]))

get_axis_limits_and_ticks <- function(axis.lim, min.val, max.val, grid.breaks, exponentiate) {
  # axis limits
  if (is.null(axis.lim)) {
    lower_lim <- min.val * .95
    upper_lim <- max.val * 1.05
  } else {
    lower_lim <- axis.lim[1]
    upper_lim <- axis.lim[2]
  }
  
  # determine gridbreaks
  if (is.null(grid.breaks)) {
    if (exponentiate) {
      # use pretty distances for log-scale
      ticks <- grDevices::axisTicks(log(c(lower_lim, upper_lim)), log = TRUE)
      # make sure that scale is not too wide
      ticks <- ticks[1:which(ticks > max.val)[1]]
    } else {
      ticks <- pretty(c(lower_lim, upper_lim))
    }
  } else {
    ticks <- seq(lower_lim, upper_lim, by = grid.breaks)
  }
  
  # save proper axis limits
  list(axis.lim = c(min(ticks), max(ticks)), ticks = ticks)
}
#s$coefficients[,5]
    if (!show.intercept) 
      fl <- purrr::map(fl, ~dplyr::slice(.x, -1))
  
  if (exponentiate) 
    fl <- purrr::map(fl, function(x) {
      x[["estimate"]] <- exp(x[["estimate"]])
      x[["conf.low"]] <- exp(x[["conf.low"]])
      x[["conf.high"]] <- exp(x[["conf.high"]])
      x
    })
  for (i in 1:length(fl)) fl[[i]] <- tibble::add_column(fl[[i]], 
                                                        group = as.character(i))
  ff <- dplyr::bind_rows(fl)
  if (!is.null(std.est) && std.est == "std2") 
    ff$term <- substring(ff$term, first = 3)
  if (!is.null(rm.terms)) 
    ff <- subset(ff,!(ff$term %in% rm.terms))
  if (is.null(m.labels)) 
    m.labels <- sjlabelled::get_dv_labels(input_list)
  m.labels <- sjmisc::word_wrap(m.labels, wrap = wrap.labels)
  if (anyDuplicated(m.labels) > 0) 
    m.labels <- suppressMessages(tibble::tidy_names(m.labels))
  ff$group <- as.factor(ff$group)
  levels(ff$group) <- m.labels
#  ff$group <- forcats::fct_rev(ff$group)
  
  if (!is.null(thatorder)) ff$term <- forcats::fct_relevel(ff$term, thatorder)
  
  ff$term <- forcats::fct_rev(ff$term)
  
  ff$p.stars <- get_p_stars(ff$p.value)
  ff$p.label <- sprintf("%.*f", digits, ff$estimate)
  if (show.p) 
    ff$p.label <- sprintf("%s %s", ff$p.label, ff$p.stars)
  if (p.shape) 
    p <- ggplot(ff, aes_string(x = "term", y = "estimate", 
                               colour = "group", shape = "p.stars"))
  else p <- ggplot(ff, aes_string(x = "term", y = "estimate", 
                                  colour = "group"))
  p <- p + geom_hline(yintercept = 0, 
                       linetype = vline.type, 
                       color = vline.color) + 
    geom_point(position = position_dodge(geom.spacing), size = geom.size) + 
    geom_errorbar(aes_string(ymin = "conf.low2", 
                             ymax = "conf.high2"), 
                  position = position_dodge(geom.spacing), width = 0) + 
    coord_flip() + 
    guides(colour = guide_legend(reverse = TRUE))
  
  get_estimate_axis_title <- function(fit, axis.title) {
    # check if we have a linear model
    is.linear.model <- any(inherits(fit, c("lm", "lmerMod", "lme"), which = TRUE) == 1)
    
    if (!is.linear.model) {
      # get information of glm
      fitfam <- get_glm_family(fit)
      
      # create logical for family
      poisson_fam <- fitfam$is_pois
      binom_fam <- fitfam$is_bin
      logit_link <- fitfam$is_logit
    }
    
    # check default label and fit family
    if (is.null(axis.title)) {
      if (is.linear.model)
        axis.title <- "Estimates"
      else if (poisson_fam)
        axis.title <- "Incident Rate Ratios"
      else if (binom_fam && !logit_link)
        axis.title <- "Risk Ratios"
      else
        axis.title <- "Odds Ratios"
    }
    
    axis.title
  }
  
  col_check2 <- function(geom.colors, collen) {
    # --------------------------------------------
    # check color argument
    # --------------------------------------------
    # check for corrct color argument
    if (!is.null(geom.colors)) {
      # check for color brewer palette
      #if (is.brewer.pal(geom.colors[1])) {
      if (TRUE) {
        geom.colors <- scales::brewer_pal(palette = geom.colors[1])(collen)
      } 
      else if (geom.colors[1] == "gs") {
        geom.colors <- scales::grey_pal()(collen)
        # do we have correct amount of colours?
      } else if (geom.colors[1] == "bw") {
        geom.colors <- rep("black", times = collen)
        # do we have correct amount of colours?
      } else if (length(geom.colors) > collen) {
        # shorten palette
        geom.colors <- geom.colors[1:collen]
      } else if (length(geom.colors) < collen) {
        # warn user abount wrong color palette
        warning(
          sprintf(
            "Insufficient length of color palette provided. %i color values needed.",
            collen
          ),
          call. = F
        )
        # set default palette
        geom.colors <- scales::brewer_pal(palette = "Set1")(collen)
      }
    } else {
      geom.colors <- scales::brewer_pal(palette = "Set1")(collen)
    }
    
    geom.colors
  }
  
  if (p.shape) 
    p <- p + scale_shape_manual(values = c(1, 16, 17, 15), 
                                labels = c("n.s.", "*", "**", "***"))
  if (show.values) 
    p <- p + geom_text(aes_string(label = "p.label"), position = position_dodge(geom.spacing), 
                       vjust = geom.spacing * labelv, hjust = labelh, show.legend = FALSE, size = labelsize)
  if (is.null(axis.labels)) 
    axis.labels <- sjlabelled::get_term_labels(input_list)
  p <- p + scale_x_discrete(labels = sjmisc::word_wrap(axis.labels, 
                                                       wrap = wrap.labels))
  if (!show.legend) 
    p <- p + guides(colour = "none", shape = "none")
  if (facet.grid) 
    p <- p + facet_grid(~group)
  axis.scaling <- get_axis_limits_and_ticks(axis.lim = axis.lim, 
                                            min.val = min(ff$conf.low2), max.val = max(ff$conf.high2), 
                                            grid.breaks = grid.breaks, exponentiate = exponentiate)
  #if (exponentiate) {
  #  p <- p + scale_y_continuous(trans = "log10", limits = axis.scaling$axis.lim, 
  #                              breaks = axis.scaling$ticks, labels = prettyNum)
  #}
  #else {
  #  p <- p + scale_y_continuous(limits = axis.scaling$axis.lim, 
  #                              breaks = axis.scaling$ticks, 
  #                              labels = axis.scaling$ticks)
  p <- p + scale_y_continuous(limits = axis.scaling$axis.lim)
  #}
 # p <- p + scale_colour_manual(values = col_check2(geom.colors, 
#                                                   length(m.labels)))
 # p <- p + scale_colour_manual(values = palette(rainbow(18)))
  if (!is.null(col_mods)) {
    p <- p + scale_colour_manual(values = c(rep(col_mods[1], 4), 
                                            col_mods[2], 
                                            rep(col_mods[1], 2), 
                                            rep(col_mods[2], 5), 
                                            rep(col_mods[3], 6)))  
  } else {
  p <- p + scale_colour_manual(values = plot_colors)
  }
  
  p <- p + labs(x = NULL, 
                y = sjmisc::word_wrap(
                  get_estimate_axis_title(
                    input_list[[1]], 
                    axis.title), 
                  wrap = wrap.title), 
                title = sjmisc::word_wrap(title, 
                wrap = wrap.title), 
                colour = sjmisc::word_wrap(legend.title, 
                wrap = wrap.legend.title), 
                shape = sjmisc::word_wrap(legend.pval.title, 
                wrap = wrap.legend.title))
  p
}

```



# Regressions

## Null Model

```{r}
fit0 <- lmer(gov_trust_high ~ 1 +
                 (1|cntry), data = combined, weights = weight)

icc(fit0)
```


## W/O Controls

```{r}


delibs <- combined %>% select(delib10, consult10, reason10, common10, countr10, engage10)

multilevels <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined, weights = weight)
  return(result)
}

multilevels_dem <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_dem, weights = weight)
  return(result)
}

multilevels_aut <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_aut, weights = weight)
  return(result)
}

mods1 <- names(delibs) %>% 
  purrr::map(multilevels)

mods2 <- names(delibs) %>% 
  purrr::map(multilevels_dem)

mods3 <- names(delibs) %>% 
  purrr::map(multilevels_aut)

listing <- function(...) {
  rlist::list.flatten(rlist::list.append(...))
}

#list.flatten(list.append(mods1, mods2, mods3))

anorder <- c("delib10", "reason10", "common10", "countr10", "consult10", "engage10")

plot_models2(listing(mods1, mods2, mods3),
             thatorder = anorder,
             col_mods = c("#24C724", "#282BD4", "#F71818"),
#             plot_colors = c("green","green","green","green","blue","green",
#                             "green","blue","blue","blue","blue","blue",
#                             "red","red","red","red","red","red"),
             exponentiate = F, std.est = "std", 
             rm.terms = c("sex","income","educ", 
                           "work", "age", "sex",
            "afro", "latino", "americas", "asian", "ESS"), 
            show.values = T, show.p = T,
            labelv = -0.3, 
            labelh = -0.9, 
            labelsize = 3.2,
            geom.size = 3, geom.spacing = 0.8, 
            show.legend = F) + 
            #geom.colors = palette(rainbow(18)) + 
            theme_economist_white() + 
            theme(legend.position = "right") 


```
## With Controls

```{r}

delibs <- combined %>% select(delib10, consult10, reason10, common10, countr10, engage10)


multilevels_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i +
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined, weights = weight)
  return(result)
}

multilevels_dem_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i +
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_dem, weights = weight)
  return(result)
}

multilevels_aut_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + 
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_aut, weights = weight)
  return(result)
}

mods1_c <- names(delibs) %>% 
  purrr::map(multilevels_c)

mods2_c <- names(delibs) %>% 
  purrr::map(multilevels_dem_c)

mods3_c <- names(delibs) %>% 
  purrr::map(multilevels_aut_c)

listing <- function(...) {
  rlist::list.flatten(rlist::list.append(...))
}

#list.flatten(list.append(mods1, mods2, mods3))

anorder <- c("delib10", "reason10", "common10", "countr10", "consult10", "engage10")

plot_models2(listing(mods1_c, mods2_c, mods3_c),
             thatorder = anorder,
             col_mods = c("#24C724", "#282BD4", "#F71818"),
#             plot_colors = c("green","green","green","green","blue","green",
#                             "green","blue","blue","blue","blue","blue",
#                             "red","red","red","red","red","red"),
             exponentiate = F, std.est = "std", 
             rm.terms = c("sex","income","educ", 
                           "work", "age", "sex",
            "afro", "latino", "americas", "asian", "ESS",
            "ethnic10", "pop10"), 
            show.values = T, show.p = T,
            labelv = -0.3, 
            labelh = -0.9, 
            labelsize = 3.2,
            geom.size = 3, geom.spacing = 0.8, 
            show.legend = F) + 
            #geom.colors = palette(rainbow(18)) + 
            theme_economist_white() + 
            theme(legend.position = "right") 

```

## With Polity Controls

### the right order has to be established

```{r}

delibs <- combined %>% select(delib10, consult10, reason10, common10, countr10, engage10)


multilevels_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + polity_demdummy + polity_autodummy +
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined, weights = weight)
  return(result)
}

multilevels_dem_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + polity10 +
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_dem, weights = weight)
  return(result)
}

multilevels_aut_c <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + polity10 +
                   ethnic10 + pop10 + #gdp10 + 
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_aut, weights = weight)
  return(result)
}

mods1_c <- names(delibs) %>% 
  purrr::map(multilevels_c)

mods2_c <- names(delibs) %>% 
  purrr::map(multilevels_dem_c)

mods3_c <- names(delibs) %>% 
  purrr::map(multilevels_aut_c)

listing <- function(...) {
  rlist::list.flatten(rlist::list.append(...))
}

#list.flatten(list.append(mods1, mods2, mods3))

anorder <- c("delib10", "reason10", "common10", "countr10", "consult10", "engage10")

plot_models2(listing(mods1_c, mods2_c, mods3_c),
             thatorder = anorder,
             col_mods = c("#24C724", "#282BD4", "#F71818"),
#             plot_colors = c("green","green","green","green","blue","green",
#                             "green","blue","blue","blue","blue","blue",
#                             "red","red","red","red","red","red"),
             exponentiate = F, std.est = "std", 
             rm.terms = c("sex","income","educ", 
                           "work", "age", "sex",
            "afro", "latino", "americas", "asian", "ESS",
            "ethnic10", "pop10", 
            "polity_autodummy", "polity_demdummy", "polity10"), 
            show.values = T, show.p = T,
            labelv = -0.3, 
            labelh = -0.9, 
            labelsize = 3.2,
            geom.size = 3, geom.spacing = 0.8, 
            show.legend = F) + 
            #geom.colors = palette(rainbow(18)) + 
            theme_economist_white() + 
            theme(legend.position = "right") 

```






# Try Out

```{r}
delibs <- combined %>% select(delib10, consult10, reason10, common10, countr10, engage10)

multilevels <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + ethnic10 + gdp10 + corrupt10 + lifeexp10 +
               work10 + #glob10 + 
         #        poly10 + 
                 #polity_demdummy + polity_autodummy +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined, weights = weight)
  return(result)
}  

multilevels_dem <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + ethnic10 + gdp10 + corrupt10 + lifeexp10 +
               work10 + #glob10 + 
          #       poly10 + 
                 #polity_demdummy + polity_autodummy +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_dem, weights = weight)
  return(result)
}

multilevels_aut <- function(delibs) {
  result <- lmer(substitute(gov_trust_high ~ income + educ + 
               work + age + sex + i + ethnic10 + gdp10 + corrupt10 + lifeexp10 +
               work10 + #glob10 + 
            #     poly10 + 
                 #polity_demdummy + polity_autodummy +
                 afro + latino + americas + asian + ESS +
                 (1|cntry), list(i = as.name(delibs))) , data = combined_aut, weights = weight)
  return(result)
}


mods_all <- names(delibs) %>% 
  purrr::map(multilevels)

mods_d <- names(delibs) %>% 
  purrr::map(multilevels_dem)

mods_a <- names(delibs) %>% 
  purrr::map(multilevels_aut)

anorder <- c("delib10", "reason10", "common10", "countr10", "consult10", "engage10")

plot_models2(listing(mods_all, mods_d, mods_a),
             thatorder = anorder,
             col_mods = c("#24C724", "#282BD4", "#F71818"),
#             plot_colors = c("green","green","green","green","blue","green",
#                             "green","blue","blue","blue","blue","blue",
#                             "red","red","red","red","red","red"),
             exponentiate = F, std.est = "std", 
             rm.terms = c("sex","income","educ", 
                           "work", "age", "sex",
            "afro", "latino", "americas", "asian", "ESS"), 
            show.values = T, show.p = T,
            labelv = -0.3, 
            labelh = -0.9, 
            labelsize = 3.2,
            geom.size = 3, geom.spacing = 0.8, 
            show.legend = F) + 
            #geom.colors = palette(rainbow(18)) + 
            theme_economist_white() + 
            theme(legend.position = "right") 

vif.mer(mods_all[[3]])

hist(combined$poly10)

fit0 <- lmer(gov_trust_high ~ income + educ + 
               work + age + sex + ethnic10 + gdp10 + corrupt10 + lifeexp10 +
               work10 + #glob10 + 
                 polity10 + 
                 #polity_demdummy + polity_autodummy +
                 afro + latino + americas + asian + ESS + (1|cntry), data = combined, weights = weight)

plot_model(fit0)
```

