---
title: "Tables"
output: html_notebook
---

# Loading the Packages

```{r}
library(pacman)

#p_install_gh("favstats/favstats")
p_load(tidyverse, haven,sjmisc,
                     forcats, weights, car,
                     countrycode, reshape2, 
                     magrittr)

range01 <- function(x){(x-min(x, na.rm = T))/(max(x, na.rm = T)-min(x, na.rm = T))}
specify_decimal <- function(x, k) trimws(format(round(x, k), nsmall=k))

options(xtable.sanitize.rownames.function = identity)
options(xtable.sanitize.colnames.function = identity)
options(xtable.sanitize.text.function = identity)
load("data/combined.Rdata")


```

# Correlation Table

```{r}
make_bold <- function(makethisbold) {
 makethisbold <- specify_decimal(makethisbold, 2)
  if (makethisbold <= 0.5) {
  return(paste0("\\textbf{", makethisbold, "}"))
  } else return(makethisbold)
}

make_italic <- function(makethisitalic) {
# makethisitalic <- specify_decimal(makethisitalic, 2)
  return(paste0("\\textit{", makethisitalic, "}"))
}

combined %>% 
  select(delib10:engage10, polity10) %>% 
  mutate_all(as.numeric) -> combined_all_table

cormat_all <- round(cor(combined_all_table, use = "pairwise.complete.obs"),3)

combined %>% 
  filter(regime == "demo") %>% 
  select(delib10:engage10, polity10) %>% 
  mutate_all(as.numeric) -> combined_demo_table

cormat_dem <- round(cor(combined_demo_table, use = "pairwise.complete.obs"),3)

combined %>% 
  filter(regime != "demo") %>% 
  select(delib10:engage10, polity10) %>% 
  mutate_all(as.numeric) -> combined_nondemo_table

cormat_nondem <- round(cor(combined_nondemo_table, use = "pairwise.complete.obs"),3)


rbind(
cormat_all %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "polity10") %>% 
  mutate(cor_with = paste0("Complete Data (n=", nrow(combined %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:polity10), make_bold) %>% 
  mutate_at(vars(delib10:polity10), make_italic),


cormat_dem %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "polity10") %>% 
  mutate(cor_with = paste0("Democracies (n=", nrow(combined %>% 
                                                      filter(regime == "demo") %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:polity10), make_bold) %>% 
  mutate_at(vars(delib10:polity10), make_italic),



cormat_nondem %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "polity10") %>% 
  mutate(cor_with = paste0("Non-Democracies (n=", nrow(combined %>% 
                                                      filter(regime != "demo") %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:polity10), make_bold) %>% 
  mutate_at(vars(delib10:polity10), make_italic)
) -> combined_table

combined_table %<>% 
  column_to_rownames("cor_with") %>% 
  select(delib10, reason10, common10, countr10, consult10, engage10, polity10)
colnames(combined_table) <- c("\\textbf{DCI}", 
                              "\\textbf{RJ}", 
                              "\\textbf{CG}", 
                              "\\textbf{CA}", 
                              "\\textbf{RoC}", 
                              "\\textbf{ES}", 
                              "\\textbf{Polity/FH}") 

library(xtable)
combined_latex <- xtable(combined_table)

print(combined_latex, booktabs = T)
```

## cite_corr

```{r}
rbind(
cormat_all %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  filter(sample == "polity10") %>% 
  mutate(sample = "complete"),
cormat_dem %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  filter(sample == "polity10") %>% 
  mutate(sample = "dems"),
cormat_nondem %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  filter(sample == "polity10") %>% 
  mutate(sample = "nondems")
)  %>% 
  select(sample, delib10, reason10, common10, countr10, 
         consult10, engage10, polity10) -> combined_cite

combined_cite %>% 
  filter(sample == "complete") %>% 
  select(delib10) %>% 
  .$delib10

save(combined_cite, file = "text/data/combined_cite.Rdata")

cite_corr <- function(delib_indicator, sample) {
  # delib_indicator <- enquo(delib_indicator)
  # cor_with <- enquo(cor_with)
  combined_cite %>% 
    filter(sample == !!sample) %>% 
    select_(delib_indicator) %>% 
    mutate_all(~specify_decimal(., 2)) %>% 
    as.character()
}

cite_corr(delib_indicator = "delib10", sample = "complete")

```

# FoD Corr


```{r}


combined %>% 
  select(delib10:engage10, discuss) %>% 
  mutate_all(as.numeric) -> combined_all_table

cormat_all <- round(cor(combined_all_table, use = "pairwise.complete.obs"),3)

combined %>% 
  filter(regime == "demo") %>% 
  select(delib10:engage10, discuss) %>% 
  mutate_all(as.numeric) -> combined_demo_table

cormat_dem <- round(cor(combined_demo_table, use = "pairwise.complete.obs"),3)

combined %>% 
  filter(regime != "demo") %>% 
  select(delib10:engage10, discuss) %>% 
  mutate_all(as.numeric) -> combined_nondemo_table

cormat_nondem <- round(cor(combined_nondemo_table, use = "pairwise.complete.obs"),3)


rbind(
cormat_all %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "discuss") %>% 
  mutate(cor_with = paste0("Complete Data (n=", nrow(combined %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:discuss), make_bold) %>% 
  mutate_at(vars(delib10:discuss), make_italic),


cormat_dem %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "discuss") %>% 
  mutate(cor_with = paste0("Democracies (n=", nrow(combined %>% 
                                                      filter(regime == "demo") %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:discuss), make_bold) %>% 
  mutate_at(vars(delib10:discuss), make_italic),



cormat_nondem %>% 
  as.data.frame() %>% 
  rownames_to_column("cor_with") %>% 
  filter(cor_with == "discuss") %>% 
  mutate(cor_with = paste0("Non-Democracies (n=", nrow(combined %>% 
                                                      filter(regime != "demo") %>% 
                                                      select(cntry) %>% 
                                                      unique), ")")) %>% 
  mutate_at(vars(delib10:discuss), make_bold) %>% 
  mutate_at(vars(delib10:discuss), make_italic)
) -> combined_table

combined_table %<>% 
  column_to_rownames("cor_with") %>% 
  select(delib10, reason10, common10, countr10, consult10, engage10, discuss)
colnames(combined_table) <- c("\\textbf{DCI}", 
                              "\\textbf{RJ}", 
                              "\\textbf{CG}", 
                              "\\textbf{CA}", 
                              "\\textbf{RoC}", 
                              "\\textbf{ES}", 
                              "\\textbf{Freedom of Discussion}") 

library(xtable)
combined_latex <- xtable(combined_table)

print(combined_latex, booktabs = T)

load("data/macro.Rdata")
macro %>% 
#  filter(polity_demdummy != 1) %>% 
  select(mean_gov_high, discuss) %>% 
cor()
```


# Weighting

```{r}
load("data/macro.Rdata")

macro %>% 
  select(mean_gov:mean_gov_high, discuss) %>% 
  cor()

macro %>% 
  mutate(discuss_round = round(5-((macro$discuss*3)+1))) %>% 
  arrange(desc(discuss_round)) %>% 
  filter(discuss_round > 2) %>% 
  mutate(discuss_label = ifelse(discuss_round == 3, "\\textit{Somewhat Respected}", 
                                "\\textit{Weakly Respected}")) %>% 
  select(cntry, mean_gov, mean_gov_low, mean_gov_high, discuss_label) %>% 
  mutate_at(vars(mean_gov:mean_gov_high), ~round(.,2)) %>%  
  mutate_at(vars(mean_gov:mean_gov_high), ~sprintf('%.2f', ., 2)) %>% 
  arrange(desc(discuss_label), desc(mean_gov)) -> weigh_table_dat


weigh_table_latex <- xtable(weigh_table_dat)

print(weigh_table_latex, booktabs = T)

# -0.3797815   -0.2016119   -0.03967678
```

# Summary Statistics

```{r}
library(tableHTML)

load("data/macro.Rdata")

rbind(

combined %>% 
  select(income, educ, age, work, sex, gov_trust, gov_trust_low, gov_trust_high) %>% 
sjmisc::descr() %>% 
  as.data.frame() %>% 
  select(variable, n, mean, sd, md, min, max, skew, kurtosis) %>% 
  mutate(n = round(n)) %>% 
  mutate_at(vars(mean:kurtosis), ~sprintf('%.2f', ., 2)) %>% 
  mutate(variable = c(
                      "Financial Security",
                      "Education", 
                      "Age", 
                      "Employment (0/1)", 
                      "Sex (Male/Female)",
                      "Regime Support (No Bias)",
                      "Regime Support (Low Bias)", 
                      "Regime Support (High Bias)"
                      )),


macro %>% 
  select(delib10, reason10, common10, countr10, consult10, 
         engage10, polity10, lifeexp10, pop10, gdp10, corrupt10, urbanratio10, 
         polity_demdummy, polity_anodummy, polity_autodummy) %>% 
sjmisc::descr() %>% 
  as.data.frame() %>% 
  select(variable, n, mean, sd, md, min, max, skew, kurtosis) %>% 
  mutate(n = round(n)) %>% 
  mutate_at(vars(mean:kurtosis), ~sprintf('%.2f', ., 2)) %>% 
  mutate(variable = c(
                      "DCI",
                      "Reasoned Justification", 
                      "Common Good", 
                      "Counter-Arguments", 
                      "Range of Consultation",
                      "Engaged Society",
                      "Polity/FH", 
                      "Life Expectancy",
                      "logged Population",
                      "logged GDP per Capita",
                      "Corruption",
                      "Urban Population Ratio",
                      "Democracy (0/1)",
                      "Anocracy (0/1)",
                      "Autocracy (0/1)"
                      ))

) %>% 
  rename(Variable = variable, 
         N = n,
         Mean = mean,
         SD = sd,
         Median = md,
         Min = min,
         Max = max,
         Skew = skew,
         Kurtosis = kurtosis) -> html_summary 
  
save(html_summary, file = "data/html_summary.Rdata")



 








 



```

# countries

```{r}

load("data/macro.Rdata")

macro %>% 
  mutate(`ISO Code` = countrycode(cntry, "country.name", "iso3c")) %>% 
  mutate(Country = cntry) %>% 
  mutate(`Nr.` = 1:n()) %>% 
  select(Country, `ISO Code`, `Nr.`) -> country_table


save(country_table, file = "data/country_table.Rdata")


  # knitr::kable()

```




