---
title: "R Notebook"
output: html_notebook
---

## packages

```{r}
pacman::p_load(tidyverse)
```


## data

```{r}
library(gganimate)

vdem <- read_csv("C:/Users/Fabio/Documents/Country_Year_V-Dem_Extended_CSV_v8/V-Dem-CY+Others-v8.csv")


vdem %>% 
  select(country_name, country_text_id, year, v2xdl_delib, e_fh_ipolity2) %>% 
  na.omit() %>% 
  ggplot(aes(v2xdl_delib, e_fh_ipolity2)) +
  geom_point() +
  geom_smooth(method = "lm", color = "black", linetype = 2, se = F, show.legend = F) +
 # ggrepel::geom_text_repel(aes(label = country_text_id), show.legend = F) +
  geom_text(aes(label = country_text_id), show.legend = F) +
  ggthemes::theme_hc() +
  ggthemes::scale_color_gdocs() +
  # ylim(20, 110) +
  # scale_y_continuous(breaks = seq(0, 1, .2), 
  #                    limits = c(0, 1)) +
  # scale_x_continuous(breaks = seq(0, 1, .2), 
  #                    limits = c(0, 1)) +
  ylab("Polity/FH") +
  xlab("Deliberative Component Index") +
  geom_text(aes(x = 0.95, y = 0.05, label = paste0("Year:", year))) +
  transition_states(year, transition_length = 4, state_length = 1) -> ss# +
#  ggpubr::stat_cor(color = "black", label.x.npc = "left", label.y.npc = "top", show.legend = F) 


animate(ss, nframes = 300, fps = 10, length = 300)

```

