---
output: pdf_document
---

Since political theory took its “deliberative turn” [@dryzek2000deliberative] in the 1990s, empirical political science has increasingly turned towards deliberation as well. There have been numerous studies about its requirements and consequences. This paper is concerned with the latter. Deliberative theory along with empirical science has developed manifold assumptions about the effects of deliberation, including transformation of preferences, epistemic quality, consensus and accommodation, as well as side-effects on civic virtues like political trust [cf. @bachtiger2013empirisch pp. 164-165].
Given the current decline of trust in governments and political institutions in many democracies across the world [cf. @foa2016democratic], deliberation could be seen as a process to arrive at legitimate decisions in societies of increasing complexity (see for example: @habermas1994three [pp. 7-8]; @warren2015can [p. 562]). This paper seeks to investigate what can be theorized as a side-effect of deliberation: political support for the regime. This study differs from previous ones in the following terms: It is the first to examine the effects of deliberation on regime support in a cross-national framework across a large dataset of 306,047 respondents from 113 countries across all continents. Moreover, the analysis is not restricted to democratic regimes, but also includes non-democracies.^[For the purposes of this paper we consequently refer to political systems as non-democratic in accordance with the Polity IV project classification of autocracies and anocracies.] Therefore, a recent theoretical development, the conceptualization of deliberation outside of democratic contexts, so called \textit{authoritarian deliberation}, is taken into account (see: @he2014deliberative; @he2011authoritarian; @he2010giving). 

The main research question of this thesis states as follows: \textit{What role does Deliberation play for regime support across the world?} The following section establishes the theoretical framework of political support and derives possible determinants of regime support. Next, the concept of deliberation is clarified and the link between deliberation and regime support is drawn, from which hypotheses are derived (Section 2). The next section presents the research design of this study and the results of the analysis (Section 3). In the end, the findings of the analysis will be summarized and the conclusion gives an answer to the research question along with a discussion of implications for further research (Section 4).