---
output: pdf_document
---


For over twenty years, deliberation has been a topic of great interest to political theory and empirical political science. One of the main contributors to deliberative theory is the German philosopher Jürgen Habermas. His classical model of deliberation is characterized by the logic of communicative action, by which the action orientations of participants are coordinated through acts of common understanding, rather than strategic calculations regarding their own success [cf. @habermas1982theorie pp. 385]. The ideal deliberative procedure, as described by Cohen, needs to meet the following criteria [@cohen2003deliberation pp. 346-347]: First, ideal deliberation is \textit{free} in that “ [...] the participants regard themselves as bound only by results of their deliberation […]”. The second criterion is that proposals must be justified with  \textit{reasons}, with the assumption that these reasons will determine whether the proposals are accepted. The next criterion is that participants are formally and substantively \textit{equal}, meaning that the rules of the process and the distribution of power and resources do not discriminate against individuals. Lastly, deliberation’s ideal goal is to arrive at a rational \textit{consensus}. More generally speaking, this type of deliberation contains the process of rational consideration of arguments, in which the participants provide elaborate reasons that relate to the common good to justify their positions, respect other opinions and are truthful as well as willing to yield to better arguments [cf. @bachtiger2010disentangling pp. 35-37].

The discussed type of ideal deliberation is quite demanding and therefore invited criticism from different directions. @bachtiger2010disentangling [pp. 42-48] discern between the Habermasian *type I* deliberative theory and *type II* deliberation, under which they subsume criticisms and further developments. This type of deliberation contains a range of theoretical adaptations and does not resemble a unified theory. Generally, the focus changed from the deliberative process to deliberative institutions and outcomes and some of the strict requirements of the classical model are loosened or dropped completely. For example, scholars pointed out that not all citizens are equally able to convey their point of view in a way that fulfills ideal deliberative criteria, which can be dependent on factors like socio-economic background, gender or ethnicity [cf. @sanders1997against pp. 349]. Thus, one branch of type II theory introduced the admissibility of other forms of speech besides rational argumentation, as for example rhetoric, emotion, humor or storytelling [cf. @dryzek2000deliberative pp. 48]. Moreover, Mansbridge et al. argue that self-interest can sometimes be legitimate, because it doesn't necessarily violate deliberative ideals [cf. @mansbridge2010place pp. 72-73]. Other adaptations define the ideal results of deliberation in more detail and lower the threshold of admissible outcomes by focusing on meta-consensus and inter-subjective rationality instead of rationally motivated consensus [cf. @niemeyer2007ends pp. 522]. Moreover, in type II deliberation the truthfulness criterion is relaxed or abandoned entirely, as it doesn’t capture the possibility of multiple and complex intentions and is not necessary for argument accessibility or the willingness to cooperate and to change one’s opinion [cf. @markovits2006trouble pp. 257-258; @bachtiger2010disentangling p. 44].

Since this paper aims to examine the consequences of deliberation across different regime types, democracies and non-democracies alike, the relationship between democracy and deliberation needs to be examined. In the literature, deliberation is often discussed exclusively in democratic contexts, especially regarding models of deliberative democracy [@habermas1994three; @cohen2003deliberation]. In such conceptualizations, deliberation and democracy are closely linked to each other. On the other hand, critics assume an inconsistency between deliberative procedures of participation and democratic principles like equality [cf. @sanders1997against pp. 347-350; @lafont2017democracy]. For the purposes of this paper, deliberation and democracy are considered to be distinct phenomena. As Dryzek puts it: “Deliberative capacity does not have to be sought in any particular set of institutions (such as elections), but it can be manifested in different ways, in different systems” [@dryzek2009democratization pp. 1380]. We follow the conceptual approach proposed by He and Warren: democracy concerns the inclusion of individuals in matters that affect them, whereas deliberation can be conceptualized as a “communication mode in which participants in a political process offer and respond to the substance of claims, reasons, and perspectives in ways that generate persuasion-based influence” [cf. @he2011authoritarian pp. 271]. Especially in the context of non-democracies it seems appropriate to apply a type II concept of deliberation, as He and Warren do. But even then, the requirements of deliberation are more likely to be met in democracies. Moreover, the concepts do overlap in theory, as they share underlying principles like equality and a minimum guarantee of freedom of speech. Nevertheless, deliberative procedures have not only been implemented in democracies. A prominent example is China, a rather autocratic country, where deliberative practices like opinion polls or village councils have gained popularity over the last 20 years [@he2014deliberative; @he2011authoritarian; @he2010giving; @fishkin2010deliberative].^[An illustrative example is the case of deliberative polling in Zeguo Township in Wenling City, a local public consultation that attempted to affect policy choices over the funding of infrastructure projects [cf. @fishkin2010deliberative pp. 437-439]. The town leadership made the decisions of the deliberations effectively binding by committing to fund the highest rated projects, and response and participation rates were rather high. Fishkin et al. conclude, that the deliberative poll was highly representative (despite a gender bias through wrong sampling at the household stage) and met the criteria of being “scientific, democratic and legal” very well [cf. @fishkin2010deliberative pp. 446]. Moreover, and somewhat counter-intuitively, the authoritarian context proved to have some advantages: it was easier than in the usual democratic context to recruit the sample and the promise of the implementation of agreed upon results was easier to grant by the authorities [cf. @fishkin2010deliberative pp. 446].]


**Deliberation and Legitimacy**

In the literature about deliberation, the claim exists that deliberation is necessary to arrive at legitimate decisions in societies of increasing complexity [@habermas1994three; @chambers1996; @parkinson2006]. Before discussing the reasons for such claims, the concept of legitimacy needs to be defined for the purposes of this paper. So, what are legitimate decisions or outcomes? One possibility would be to  determine that every decision or outcome, arrived at through deliberative processes meeting certain quality standards, is legitimate. But when doing so, one adopts a definition which makes empirical examination redundant. So, this conceptualization of legitimacy is not of analytical interest, even though it might be most related to deliberative theory. Another approach would be to determine criteria relevant for input, throughput and output legitimacy of a political system [cf. @schmidt2013]. As we aim to explain legitimacy across a large set of nations, we chose a subjective conceptualization, focussing on legitimacy as it is perceived by the people, which makes empirical examination by cross-national survey data possible. According to this conceptualization, a state is more legitimate the more its citizens perceive it to be rightfully holding and exercising power [cf. @gilley2006 pp. 500]. This definition has the drawback of not entirely capturing the scope of legitimacy as it is conceptualized in many deliberative theories, but it is nonetheless useful as it enables the possibility to empirically examine legitimacy across a large set of cases, which is one of the central aims of this paper.

As this specification suits our approach, we chose the political support framework to further specify (and later operationalize) subjective legitimacy, which we derive from Easton [-@easton1965systems; -@easton1975re]. The underlying logic is that, if people believe their regime to be legitimate, they should have positive attitudes towards it. Easton defines political support in the following way: "We can say that A supports B either when A acts on behalf of B or when he orients himself favorably toward B; it may be a goal, idea, or institution” [@easton1965systems pp. 159]. Political support thereby relates to supportive attitudes of citizen towards the political system. Easton differentiates between three types of support objects, the \textit{political community}, \textit{political regime} and \textit{political authorities} [cf. @easton1965systems pp. 171-225]: 


\vspace{0.05cm}

> 1.	The *political community* comprises the members of a political system and the basic values represented by it. The basis of such a community is an individual’s sense of belonging and the feeling of mutual solidarity between the members of this community. 
	
>	2.	The *political regime* consists of the network of institutions that uphold a poltical system, i.e. the legislative, judicative or executive institutions. 
	
>	3.	Lastly, *political authorities* consist of the actual personalities that occupy the institutions (for example parliamentarians, heads of state). 


Where does support for the mentioned political objects come from? According to Easton, two types of support sources, \textit{diffuse} and \textit{specific}, can be distinguished [cf. @easton1975re pp. 436-439]. Specific support is sourced in the performance and outputs of a political system and its institutions. It is therefore targeted at and often dependent on the personal assessment of the current administration. On the other hand, according to Easton, diffuse support is a commitment to specific political values and norms, as well as to the concrete political structures responsible for the implementation of that political and social order. Diffuse support is therefore more robust and a more long-term source of legitimacy than specific support. For the purposes of this paper, a focus will be set on diffuse support, especially trust in the political regime, as it relates to the level on which the deliberative qualities are of analytical interest. 

Next we seek to answer the question why decisions arrived at through deliberation, or more generally speaking, political systems embodying deliberative criteria, should be more legitimate. As discussed before, the aim of deliberation is to arrive at rational consensus or at least some form of meta-consensus. This involves the transformation of preferences, which at first refers to the attitudes towards the alternative policies proposed through deliberation, ideally shifting preferences and outcomes in a direction of more publicly-spirited orientations [cf. @fishkin2009people pp. 134]. Moreover, the epistemic quality of decisions is assumed to increase when they are deliberated [cf. @bachtiger2013empirische pp. 164]. According to Cohen, participants of deliberative processes  “[...] suppose that they can act from the results, taking the fact that a certain decision is arrived at through their deliberation as a sufficient reason for complying with it” [@cohen2003deliberation pp. 346-347]. For these reasons, the outcomes of deliberative processes should be accepted and viewed as legitimate at least by the people who took part in the deliberation. For example, Habermas argues that democratic legitimacy does not arise from public deliberation alone, and emphasizes the importance communication and participation of the ones potentially affected by the decision [cf. @habermas2007 pp. 431]. However, in regard to public-spiritedness and epistemic quality of decisions, the effects could be even broader, reaching beyond the participants of such processes. Such assumptions are not shared by classical deliberative theory, nevertheless we argue that even if deliberation is restricted to the elite level, such effects could reasonably be expected. Deliberative qualities like reasoned argumentation, respect for counter arguments or common good orientation, even solely between political actors, could produce well-reasoned decisions more broadly accepted, and viewed as more legitimate by the citizenry, as they would be in the absence of such qualities. Since we chose a cross-national analysis framework, the central assumption derived for empirical examination is that the deliberative quality of a political system increases its legitimacy (perceived by the citizens), which should manifest itself in higher levels of regime support. 

At this point it has to be discussed that (like deliberation) legitimacy is mostly discussed within democratic contexts. What about deliberation in autocracies? Generally speaking, autocratic rulers (and one could argue democratic rulers too) have three means at their hands to maintain their power: repression, co-optation and legitimation [cf. @gerschewski2013pillars pp. 18]. Repression is not always possible or successful and it might only create superficial support amongst the citizenry. Co-optation is only applicable on a certain scale, as one can’t co-opt the whole citizenry, even though deliberation could be seen as an attempt to co-opt people by giving them a voice option [cf. @he2011authoritarian pp. 281]. Legitimation, however, is rooted in the people’s conviction that the system is in fact legitimate [cf. @gerschewski2013pillars pp. 18]. As discussed before, deliberation is said to be a way to generate legitimacy and therefore, deliberative practices could legitimate the political regime without adopting electoral democratic structures. An important notion in this context is that deliberation doesn’t need to be about sensitive topics, but can be used to deliberate about issues that aren’t threatening the autocratic rule, for example new community infrastructures. When decisions are made through deliberative practices, the participants might have the impression that the rulers are asking for and listening to their opinion and in turn they might perceive the regime to be more legitimate. In some cases, citizen deliberation could inform the regime about policy preferences otherwise not knowable in highly autocratic contexts and therefore enable the regime to be more responsive to the citizenry. @truex2017consultative finds such effects when conducting an online survey experiment of Chinese Netizens who were exposed to the National People’s Congress’ online participation portals. He summarizes his findings as follows: “[...] even such limited reforms may shift attitudes toward the regime in the positive direction. [...] exposure to images [...] increases satisfaction with the regime, feelings of government responsiveness, and expressed willingness to comply with regulations, but only for citizens with low political access and low expectations for government performance” [@truex2017consultative pp. 352]. The results offer some evidence for the proposed relationship, even if the examined online portals aren’t exactly deliberative by definition but rather participatory or consultative and Truex only studied short-time effects. The general argument that deliberative qualities should increase the support of a political regime, even beyond individual participants of the decision making process, can be applied to non-democracies as well. Deliberation between elites that result in reasoned justification of decisions with common good orientation might generate more legitimacy and support than a regime without these criteria would enjoy.

It should be noted that the strengthening of autocratic rule is just one possible long-term outcome of the introduction of deliberative practices and quality criteria in a political system. Deliberation might as well lead to the democratization of a regime, as frequent deliberation could increase the democratic capacity of citizens over the long run [cf. @he2011authoritarian pp. 183-184; @truex2017consultative pp. 352]. Side-effects of deliberation, like increased knowledge or efficacy, could influence the people’s perception of their political regime and at the same time increase their preference for democracy. Following this line of thought, deliberation could lead to a *loss of legitimacy* for non-democratic regimes, especially in light of Truex’ findings that positive effects of consultative online portals only applied to individuals with low political access. Therefore, the theoretical predictions for the effects of deliberation in non-democracies are contradicting, suggesting either *higher* legitimacy through deliberative qualities, or *lower* legitimacy due to an increase of democratic capacities of the citizens. For democracies specifically, we expect higher levels of political support for systems with more deliberative qualities. 