---
output: pdf_document
---

Recalling the research question, \textit{What role does Deliberation play for regime support across the world?}, a simple answer can not be given in light of the ambiguous empirical evidence. Table \ref{summaryy} summarizes the findings of this paper in regard to the research hypotheses derived from the theoretical considerations in Section 2.2. To test H1 and its sub-hypotheses, multilevel regression analyses were performed. Empirical evidence is found for Hypothesis 1, which states that the more deliberative as system is, the higher is support for the regime, though the results are not unambiguous enough to confirm H1. On the other hand, the most robust evidence was found for H1.1, which restricts H1 to democracies. Within the democracy subsample, we find clear evidence of a positive effect of the used deliberation measurement and regime support and, therefore preliminarily confirm H1.1. Concerning the contradicting sub-hypotheses H1.2a and H1.2b, we can rather confidently refer from confirming the latter one. The results, especially after controlling for Polity/FH, tend towards positive effects of the deliberation indicators and regime support within non-democracies, therefore indicating the effect proposed by H1.2a. It is suggested that further research investigates this relationship more thoroughly.
	
The general conclusion and central finding of this study is, that deliberation seems to have a positive effect on regime support, foremostly within democracies, for which the empirical evidence was the most unambiguous and robust. The results for the complete sample and non-democracy subsample bear the problem to be potentially affected by biased regime support data, or to be weighted with  a rather unexplored procedure, which might undermine the reliability of the results. Moreover, the findings are more ambiguous and less robust than within the democracy subsample, though tendencies towards a positive effect of deliberation predominate.   

**summary table**

Since there are quite some restrictions and limitations of our study, they shall be briefly discussed in regard to implications for further research. First, the self-reported regime support data are presumed to be biased, since regime support in non-democracies is investigated as well. The applied weighting to account for the bias has arbitrary cut-off values and is not tested for accuracy or validity. We therefore join @tannenberg2017autocratic and encourage further research to take possible bias into account and find possible remedies, as for example specific survey items or refined statistical methods. Another limitation of the empirical analysis is the lack of meaningful control variables on the macro level, as the ones that were included  (GDP logged, Ethnic Fractionalization, and Population, logged) in the analysis didn’t gain statistical significance or improve the model fit (Polity/FH and the Dataset-Dummies did, though).  Research building upon this analysis should make an effort to find country-level control variables stronger related to regime support. Moreover, one could consider to employ regional dummies or exclude specific sets of cases, like OECD or Western countries. The analysis is moreover limited in that it primarily focuses on between-country effects and does not appropriately account for effects within countries or capture changes within a country over time. Instead of a cross-sectional analysis, one would have to conduct a cross-sectional time-series analysis. As data on regime support is only very shortly available for a decently high amount of countries and the data isn’t always collected on a regular basis (though the WVS is a great achievement in this regard), such an analysis is hard to conduct. Especially concerning the Hypothesis 1.2a and  H1.2b, an analysis of long-time effects of increases or declines in deliberation within countries would be highly informative. Last but not least, our study might be limited in our measurement of deliberation through V-Dems DCI and its subcomponents. The validity of the measurement could be called into question, as it highly correlates with the index for democracy, Polity/FH. High correlations were expected and explainable to some degree, but a correlation of r = 0.82 (DCI with Polity/FH, complete sample) has to be evaluated critically. We suggest that scholars should, therefore, make an effort to improve the measurement of deliberation on the country-level to make it more precise and sensible, for example through including more components than just five, which every other V-Dem component index does (especially since the DCI components showed some interesting differences in their correlations with Polity/FH when investigated more thoroughly and within subgroups). Then again, we found some good news for the DCI and its components. Some of the deviations in the measures of deliberation and democracy appeared to be meaningful, with the three examples of China, Vietnam and Singapore appearing in our sample as well as in the literature as rather consultative or deliberative authoritarian polities. Moreover, expected multicollinearity wasn’t as present (or at least not directly detectable) as assumed.  In this context, it seems moreover relevant for  the findings, that the correlations of the DCI and its components with the Polity/FH measure vary between the overall correlations and the ones found in the subgroups of democracies and non-democracies, sometimes strongly. To recall two examples: Engaged Society has correlations of r = 0.77, r = 0.36 and r = 0.74, Reasoned Justification of r = 0.72, r = 0.62 and r = 0.39 in the complete, democracy and non-democracy sample, respectively. As the examination of such variations is beyond the scope of this study, we recommend further research to investigate the detected differences more thoroughly. It could be especially interesting to explore whether these findings are due to the time-period of this study, due to the facts that  the 10 year means for the variables were estimated or maybe due to the chosen democracy measurement and the classification of democracies and non-democracies. It should therefore be investigated, whether the deviations between democracy and deliberation found in this study can be reproduced in a more general context. Another suggestion would be to estimate macro-micro interactions, as the results of @truex2017consultative. indicate that positive effects of participatory processes in autocratic contexts might be restricted to the less educated and to the ones expecting less of the regime. In light of the discussed implications, we conclude that further research on relation of deliberation and regime support as well as the measurement of deliberation on the country level seems to be necessary as well as promising.
